name: WeatherBot

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 7 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Run WeatherBot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OPEN_METEO_API_KEY: ${{ secrets.OPEN_METEO_API_KEY }}
        run: java -jar target/your-bot-jar-file.jar
